ME-Model-ID: tmaritima
growth_key: mu1
complex_cofactors:
  fes_transfers:
  - SufBCD
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
trna_misacylation:
  Asn: Asp
  Gln: Glu
lipoprotein_precursors: {}
lipid_modifications: []
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents:
  5mthf_c: -0.05
  accoa_c: -5e-05
  coa_c: -6e-06
  fad_c: -1e-05
  glycogen_c: -0.154
  nad_c: -0.00215
  nadh_c: -5e-05
  nadp_c: -0.00013
  nadph_c: -0.0004
  pa160_c: -0.001398
  peptido_TM_c: -0.0276
  pgp160_c: -0.001398
  ptrc_c: -0.035
  spmd_c: -0.007
  succoa_c: -3e-06
  udcpdp_c: -0.001398
flux_of_lipid_constituents:
  TM_GL1_c: -0.003495
  TM_GL2_c: -0.003495
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- ASNTRAT
- GLNTRAT
- FMETTRS
- ATPM
gam: 25.0
m-model-path: ./tmaritima//building_data/m_model_modified.json
genbank-path: ./tmaritima//building_data/genome_modified.gb
df_gene_cplxs_mods_rxns: ./tmaritima/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./tmaritima//building_data/TUs_from_biocyc.txt
df_matrix_stoichiometry: ./tmaritima/inputs/reaction_matrix.txt
df_matrix_subrxn_stoich: ./tmaritima/inputs/subreaction_matrix.txt
df_metadata_orphan_rxns: ./tmaritima/inputs/orphan_and_spont_reactions.txt
df_metadata_metabolites: ./tmaritima/inputs/me_metabolites.txt
out_directory: ./tmaritima/
log_directory: ./tmaritima/
run_bbh_blast: false
dev_reference: false
include_pseudo_genes: true
locus_tag: old_locus_tag
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- TM0158-MONOMER
other_lipids:
- TM0573-MONOMER
default_sigma_factor: TM1451-MONOMER
rna_polymerases:
  RNAP_TM0534MONOMER:
    sigma_factor: TM0534-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_TM0902MONOMER:
    sigma_factor: TM0902-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_TM1451MONOMER:
    sigma_factor: TM1451-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
  RNAP_TM1598MONOMER:
    sigma_factor: TM1598-MONOMER
    polymerase: RNAP-CPLX_mod_zn2(1)_mod_mg2(2)
ngam: 1.0
translocation_multipliers:
  TM1461-MONOMER: {}
amino_acid_trna_synthetase:
  ala__L_c: TM1396-MONOMER
  arg__L_c: TM1093-MONOMER
  asp__L_c: TM1441-MONOMER
  cys__L_c: TM0719-MONOMER
  glu__L_c: generic_glu_ligase
  gly_c: CPLX-tRNA-GLY-LIGASE
  his__L_c: TM1090-MONOMER
  ile__L_c: TM1361-MONOMER
  leu__L_c: TM0168-MONOMER
  lys__L_c: TM1705-MONOMER
  met__L_c: TM1085-MONOMER
  phe__L_c: CPLX-tRNA-PHE-LIGASE
  pro__L_c: TM0514-MONOMER
  ser__L_c: TM1379-MONOMER
  thr__L_c: TM0740-MONOMER
  trp__L_c: TM0492-MONOMER
  tyr__L_c: TM0478-MONOMER
  val__L_c: TM1817-MONOMER
peptide_release_factors:
  UAG: TM1363-MONOMER
  UGA: TM1579-MONOMER
  UAA: generic_RF
braun's_lipoproteins: []
