ME-Model-ID: cljungdahlii
growth_key: mu1
complex_cofactors:
  fes_transfers:
  - CPLX_dummy
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
lipoprotein_precursors:
  MetQ: CLJU_c32100
lipid_modifications: []
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- Cl_biomass_DSM_WT_46p666M1
- FMETTRS
- ATPM
m-model-path: ./cljungdahlii//building_data/m_model_modified.json
genbank-path: ./cljungdahlii//building_data/genome_modified.gb
biocyc.genes: ./cljungdahlii/inputs/genes.txt
biocyc.prots: ./cljungdahlii/inputs/proteins.txt
biocyc.TUs: ./cljungdahlii/inputs/TUs.txt
biocyc.RNAs: ./cljungdahlii/inputs/RNAs.txt
biocyc.seqs: ./cljungdahlii/inputs/sequences.fasta
df_gene_cplxs_mods_rxns: ./cljungdahlii/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./cljungdahlii//building_data/TUs_from_biocyc.txt
out_directory: ./cljungdahlii/
log_directory: ./cljungdahlii/
run_bbh_blast: false
dev_reference: false
include_pseudo_genes: true
locus_tag: old_locus_tag
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- CLJU_RS04135-MONOMER
- CLJU_RS05260-MONOMER
other_lipids: []
default_sigma_factor: CLJU_RS04050-MONOMER
rna_polymerases:
  RNAP_CLJURS15950MONOMER:
    sigma_factor: CLJU_RS15950-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS02050MONOMER:
    sigma_factor: CLJU_RS02050-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS05110MONOMER:
    sigma_factor: CLJU_RS05110-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS16035MONOMER:
    sigma_factor: CLJU_RS16035-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS03350MONOMER:
    sigma_factor: CLJU_RS03350-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS04050MONOMER:
    sigma_factor: CLJU_RS04050-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS01630MONOMER:
    sigma_factor: CLJU_RS01630-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS06665MONOMER:
    sigma_factor: CLJU_RS06665-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS12765MONOMER:
    sigma_factor: CLJU_RS12765-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS16735MONOMER:
    sigma_factor: CLJU_RS16735-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS12070MONOMER:
    sigma_factor: CLJU_RS12070-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS07695MONOMER:
    sigma_factor: CLJU_RS07695-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS06015MONOMER:
    sigma_factor: CLJU_RS06015-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS19285MONOMER:
    sigma_factor: CLJU_RS19285-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS20310MONOMER:
    sigma_factor: CLJU_RS20310-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS16875MONOMER:
    sigma_factor: CLJU_RS16875-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS06045MONOMER:
    sigma_factor: CLJU_RS06045-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS06050MONOMER:
    sigma_factor: CLJU_RS06050-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS07935MONOMER:
    sigma_factor: CLJU_RS07935-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS02545MONOMER:
    sigma_factor: CLJU_RS02545-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS02550MONOMER:
    sigma_factor: CLJU_RS02550-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS13055MONOMER:
    sigma_factor: CLJU_RS13055-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS14740MONOMER:
    sigma_factor: CLJU_RS14740-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS18020MONOMER:
    sigma_factor: CLJU_RS18020-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
  RNAP_CLJURS13580MONOMER:
    sigma_factor: CLJU_RS13580-MONOMER
    polymerase: CPLX271D-23_mod_zn2(1)_mod_mg2(2)
ngam: 0.45
gam: 46.666
translocation_multipliers:
  CLJU_RS21155-MONOMER:
    CLJU_c02440: 2.0
amino_acid_trna_synthetase:
  ala__L_c: CLJU_RS05960-MONOMER
  arg__L_c: CLJU_RS10650-MONOMER
  asn__L_c: CLJU_RS20700-MONOMER
  asp__L_c: CLJU_RS16590-MONOMER
  cys__L_c: generic_cys_ligase
  gln__L_c: CLJU_RS13180-MONOMER
  glu__L_c: CLJU_RS06575-MONOMER
  gly_c: CLJU_RS20425-MONOMER
  his__L_c: CLJU_RS16595-MONOMER
  ile__L_c: CLJU_RS00920-MONOMER
  leu__L_c: CLJU_RS01345-MONOMER
  lys__L_c: CLJU_RS20435-MONOMER
  met__L_c: CLJU_RS00840-MONOMER
  phe__L_c: CPLX271D-6
  pro__L_c: generic_pro_ligase
  ser__L_c: CLJU_RS00085-MONOMER
  thr__L_c: CLJU_RS16995-MONOMER
  trp__L_c: CLJU_RS18860-MONOMER
  tyr__L_c: generic_tyr_ligase
  val__L_c: CLJU_RS17105-MONOMER
peptide_release_factors:
  UAG: CLJU_RS01105-MONOMER
  UGA: CLJU_RS01290-MONOMER
  UAA: generic_RF
braun's_lipoproteins: []
