ME-Model-ID: ecoli
growth_key: mu1
complex_cofactors:
  fes_transfers:
  - EG12332-MONOMER
  - EG11378-MONOMER
  - EG12132-MONOMER
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
lipoprotein_precursors:
  AcrA: b0463
  AcrE: b3265
  BamB: b2512
  BamC: b2477
  BamD: b2595
  BamE: b2617
  CusC: b0572
  EG10544-MONOMER: b1677
  EmtA: b1193
  LolB: b1209
  MetQ: b0197
  MltA: b2813
  MltB: b2701
  MltC: b2963
lipid_modifications:
- pg120_p
- pg140_p
- pg141_p
- pg160_p
- pg161_p
- pg180_p
- pg181_p
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- Ec_biomass_iJO1366_core_53p95M
- FMETTRS
- ATPM
m-model-path: ./ecoli//building_data/m_model_modified.json
genbank-path: ./ecoli//building_data/genome_modified.gb
biocyc.genes: ./ecoli/inputs/genes.txt
biocyc.prots: ./ecoli/inputs/proteins.txt
biocyc.TUs: ./ecoli/inputs/TUs.txt
biocyc.RNAs: ./ecoli/inputs/RNAs.txt
biocyc.seqs: ./ecoli/inputs/sequences.fasta
df_gene_cplxs_mods_rxns: ./ecoli/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./ecoli//building_data/TUs_from_biocyc.txt
out_directory: ./ecoli/
log_directory: ./ecoli/
run_bbh_blast: false
dev_reference: false
include_pseudo_genes: true
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- EG12128-MONOMER
- EG10548-MONOMER
other_lipids:
- EG10168-MONOMER
default_sigma_factor: RpoD_mono
rna_polymerases:
  RNAP_RpoHmono:
    sigma_factor: RpoH_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoSmono:
    sigma_factor: RpoS_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoEmono:
    sigma_factor: RpoE_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_FliAmono:
    sigma_factor: FliA_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoNmono:
    sigma_factor: RpoN_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_FecImono:
    sigma_factor: FecI_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
  RNAP_RpoDmono:
    sigma_factor: RpoD_mono
    polymerase: hRNAP_mod_zn2(1)_mod_mg2(2)
ngam: 3.15
gam: 53.95
translocation_multipliers:
  EG11197-MONOMER:
    b1855: 2.0
    b3731: 2.0
  EG11305-MONOMER:
    b4072: 20.0
    b1475: 5.166666666666667
    b1474: 5.166666666666667
    b2817: 22.0
    b0973: 14.0
    b0972: 14.0
    b0997: 13.5
    b3893: 15.5
    b0152: 21.0
    b3894: 15.5
    b1589: 14.0
    b1588: 15.0
    b2938: 6.25
    b1587: 14.0
    b1872: 26.0
    b2997: 14.0
    b2996: 21.0
    b2994: 14.0
    b2435: 20.0
    b0894: 26.0
    b0123: 23.0
    b2206: 27.0
    b2205: 20.0
  G7806-MONOMER:
    b4072: 20.0
    b1475: 5.166666666666667
    b1474: 5.166666666666667
    b2817: 22.0
    b0973: 14.0
    b0972: 14.0
    b0997: 13.5
    b3893: 15.5
    b0152: 21.0
    b3894: 15.5
    b1589: 14.0
    b1588: 15.0
    b2938: 6.25
    b1587: 14.0
    b1872: 26.0
    b2997: 14.0
    b2996: 21.0
    b2994: 14.0
    b2435: 20.0
    b0894: 26.0
    b0123: 23.0
    b2206: 27.0
    b2205: 20.0
amino_acid_trna_synthetase:
  ala__L_c: Ala_RS_tetra
  arg__L_c: ArgS_mono
  asn__L_c: Asn_RS_dim
  asp__L_c: Asp_RS_dim
  cys__L_c: generic_cys_ligase
  gln__L_c: CPLX_dummy
  glu__L_c: generic_glu_ligase
  gly_c: CPLX-tRNA-GLY-LIGASE
  his__L_c: His_RS_dim
  ile__L_c: IleS_mono
  leu__L_c: LeuS_mono
  lys__L_c: generic_lys_ligase
  met__L_c: Met_RS_dim
  phe__L_c: CPLX-tRNA-PHE-LIGASE
  pro__L_c: Pro_RS_dim
  ser__L_c: CPLX_dummy
  thr__L_c: Thr_RS_dim
  trp__L_c: Trp_RS_dim
  tyr__L_c: Tyr_RS_dim
  val__L_c: ValS_mono
peptide_release_factors:
  UAG: PrfA_mono
  UGA: PrfB_mono
  UAA: generic_RF
braun's_lipoproteins:
- EG10544-MONOMER
