ME-Model-ID: selongatus
growth_key: mu1
complex_cofactors:
  fes_transfers:
  - SYNPCC7942_0909-MONOMER
  biotin_subreactions:
    mod_btn_c:
    - biotin_ligase
  lipoate_subreactions:
    mod_lipoyl_c:
    - lipoyl_denovo
    - lipoyl_scavenging
  fes_chaperones: {}
  bmocogdp_chaperones: {}
  FeFe/NiFe:
    mod_FeFe_cofactor_c: ''
    mod_NiFe_cofactor_c: ''
lipoprotein_precursors:
  MltA: SYNPCC7942_RS02000
lipid_modifications: []
unmodeled_protein_fraction: 0.36
flux_of_biomass_constituents: {}
flux_of_lipid_constituents: {}
braun's_lipoprotein: []
braun's_lpp_flux: -0.0
braun's_murein_flux: -0.0
gr_data_doublings_per_hour:
- 0
- 0.6
- 1.0
- 1.5
- 2.0
- 2.5
percent_dna_data:
- 0.0592
- 0.0512
- 0.033
- 0.0252
- 0.0222
- 0.0208
defer_to_rxn_matrix:
- BIOMASS__1
- FMETTRS
- ATPM
m-model-path: ./selongatus//building_data/m_model_modified.json
genbank-path: ./selongatus//building_data/genome_modified.gb
biocyc.genes: ./selongatus/inputs/genes.txt
biocyc.prots: ./selongatus/inputs/proteins.txt
biocyc.TUs: ./selongatus/inputs/TUs.txt
biocyc.RNAs: ./selongatus/inputs/RNAs.txt
biocyc.seqs: ./selongatus/inputs/sequences.fasta
df_gene_cplxs_mods_rxns: ./selongatus/building_data/automated-org-with-refs.xlsx
df_TranscriptionalUnits: ./selongatus//building_data/TUs_from_biocyc.txt
out_directory: ./selongatus/
log_directory: ./selongatus/
run_bbh_blast: false
dev_reference: false
include_pseudo_genes: true
feasibility_mu: 0.01
selenocysteine_enzymes:
- CPLX_dummy
pg_pe_160:
- SYNPCC7942_1230-MONOMER
- SYNPCC7942_1726-MONOMER
other_lipids:
- SYNPCC7942_1172-MONOMER
default_sigma_factor: SYNPCC7942_0649-MONOMER
rna_polymerases:
  RNAP_SYNPCC79421510MONOMER:
    sigma_factor: SYNPCC7942_1510-MONOMER
    polymerase: CPLX490-121
  RNAP_SYNPCC79420649MONOMER:
    sigma_factor: SYNPCC7942_0649-MONOMER
    polymerase: CPLX490-121
  RNAP_SYNPCC79420569MONOMER:
    sigma_factor: SYNPCC7942_0569-MONOMER
    polymerase: CPLX490-121
  RNAP_SYNPCC79421784MONOMER:
    sigma_factor: SYNPCC7942_1784-MONOMER
    polymerase: CPLX490-121
  RNAP_SYNPCC79421557MONOMER:
    sigma_factor: SYNPCC7942_1557-MONOMER
    polymerase: CPLX490-121
  RNAP_SYNPCC79420672MONOMER:
    sigma_factor: SYNPCC7942_0672-MONOMER
    polymerase: CPLX490-121
  RNAP_SYNPCC79421746MONOMER:
    sigma_factor: SYNPCC7942_1746-MONOMER
    polymerase: CPLX490-121
  RNAP_CPLX4903613:
    sigma_factor: CPLX490-3613
    polymerase: CPLX490-121
  RNAP_CPLX4903610:
    sigma_factor: CPLX490-3610
    polymerase: CPLX490-121
  RNAP_CPLX4903607:
    sigma_factor: CPLX490-3607
    polymerase: CPLX490-121
  RNAP_CPLX4903604:
    sigma_factor: CPLX490-3604
    polymerase: CPLX490-121
  RNAP_CPLX4903611:
    sigma_factor: CPLX490-3611
    polymerase: CPLX490-121
  RNAP_CPLX4903608:
    sigma_factor: CPLX490-3608
    polymerase: CPLX490-121
  RNAP_CPLX4903605:
    sigma_factor: CPLX490-3605
    polymerase: CPLX490-121
  RNAP_CPLX4903612:
    sigma_factor: CPLX490-3612
    polymerase: CPLX490-121
  RNAP_CPLX4903609:
    sigma_factor: CPLX490-3609
    polymerase: CPLX490-121
  RNAP_CPLX4903606:
    sigma_factor: CPLX490-3606
    polymerase: CPLX490-121
  RNAP_SYNPCC79421849MONOMER:
    sigma_factor: SYNPCC7942_1849-MONOMER
    polymerase: CPLX490-121
ngam: 1.0
gam: 30.0
translocation_multipliers:
  SYNPCC7942_1617-MONOMER:
    SYNPCC7942_RS11775: 2.0
amino_acid_trna_synthetase:
  ala__L_c: SYNPCC7942_0876-MONOMER
  arg__L_c: SYNPCC7942_1577-MONOMER
  asn__L_c: SYNPCC7942_0830-MONOMER
  asp__L_c: SYNPCC7942_1313-MONOMER
  cys__L_c: SYNPCC7942_1662-MONOMER
  gln__L_c: CPLX_dummy
  glu__L_c: generic_glu_ligase
  gly_c: CPLX490-33
  his__L_c: generic_his_ligase
  ile__L_c: SYNPCC7942_2437-MONOMER
  leu__L_c: SYNPCC7942_1920-MONOMER
  lys__L_c: SYNPCC7942_2415-MONOMER
  met__L_c: SYNPCC7942_1142-MONOMER
  phe__L_c: CPLX490-27
  pro__L_c: SYNPCC7942_1959-MONOMER
  ser__L_c: SYNPCC7942_0449-MONOMER
  thr__L_c: SYNPCC7942_2606-MONOMER
  trp__L_c: SYNPCC7942_1308-MONOMER
  tyr__L_c: SYNPCC7942_2570-MONOMER
  val__L_c: SYNPCC7942_0587-MONOMER
peptide_release_factors:
  UAG: SYNPCC7942_2203-MONOMER
  UGA: SYNPCC7942_0404-MONOMER
  UAA: generic_RF
braun's_lipoproteins: []
